version: 2

before:
  hooks:
    - cargo install --locked cargo-zigbuild
builds:
  - binary: kamut
    builder: rust
    id: kamut
    targets:
      - aarch64-apple-darwin
      - x86_64-unknown-linux-gnu
    flags:
      - --release

checksum:
  name_template: "checksums.txt"

changelog:
  sort: asc
  filters:
    exclude:
      - "^docs:"
      - "^test:"
      - "^ci:"
      - "^chore:"
      - Merge pull request
      - Merge branch

release:
  github:
    owner: anarcher
    name: kamut
  prerelease: auto
  draft: false
