[package]
name = "kamut"
version = "0.1.0"
edition = "2021"

[dependencies]
serde = { version = "1.0", features = ["derive"] }
serde_yaml = "0.9"
clap = { version = "4.4", features = ["derive"] }
anyhow = "1.0"
glob = "0.3"
k8s-openapi = { version = "0.21.0", features = ["v1_28"] }
