name: app-frontend
kind: Deployment
image: nginx:1.19
env:
  APP_ENV: production
resources:
  requests:
    cpu: 200m
    memory: 200Mi
  limits:
    cpu: 500m
    memory: 500Mi
replicas: 3
node_selector:
  group: frontend