apiVersion: monitoring.coreos.com/v1
kind: Prometheus
metadata:
  labels:
    app: prometheus-self
  name: prometheus-self
  namespace: monitoring
spec:
  image: prom/prometheus:v2.42.0
  nodeSelector:
    group: monitoring
  replicas: 1
  resources:
    limits:
      cpu: 1000m
      memory: 2Gi
    requests:
      cpu: 500m
      memory: 500Mi
  retention: 30d
  scrapeConfigSelector:
    matchLabels: {}
  securityContext:
    fsGroup: 2000
    runAsNonRoot: true
    runAsUser: 1000
  serviceAccountName: prometheus-prometheus-self
  storage:
    volumeClaimTemplate:
      spec:
        resources:
          requests:
            storage: 100Gi
        storageClassName: gp3-prom
  tolerations:
  - effect: NoSchedule
    key: group
    operator: Equal
    value: monitoring

---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: prometheus-self
  name: prometheus-prometheus-self
  namespace: monitoring
spec:
  ports:
  - name: web
    port: 9090
    protocol: TCP
    targetPort: 9090
  selector:
    prometheus: prometheus-self
  type: ClusterIP

---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  labels:
    app: prometheus-self
  name: prometheus-self-ingress
  namespace: monitoring
spec:
  rules:
  - host: prometheus.example.com
    http:
      paths:
      - backend:
          service:
            name: prometheus-prometheus-self
            port:
              number: 9090
        path: /
        pathType: Prefix

---
apiVersion: v1
kind: ServiceAccount
automountServiceAccountToken: true
metadata:
  annotations:
    example.com/role: prometheus-monitoring
  labels:
    app: prometheus-self
  name: prometheus-prometheus-self
  namespace: monitoring

---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app: prometheus-self
  name: prometheus-self-role
rules:
- apiGroups:
  - ''
  resources:
  - nodes
  - nodes/proxy
  - services
  - endpoints
  - pods
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - extensions
  resources:
  - ingresses
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - networking.k8s.io
  resources:
  - ingresses
  verbs:
  - get
  - list
  - watch
- nonResourceURLs:
  - /metrics
  verbs:
  - get

---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  labels:
    app: prometheus-self
  name: prometheus-self-role-binding
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: prometheus-self-role
subjects:
- kind: ServiceAccount
  name: prometheus-prometheus-self
  namespace: monitoring
