apiVersion: monitoring.coreos.com/v1
kind: Prometheus
metadata:
  labels:
    app: example-no-retention
  name: example-no-retention
spec:
  image: prom/prometheus:v2.7.1
  replicas: 1
  resources:
    limits:
      cpu: 1000m
      memory: 2Gi
    requests:
      cpu: 500m
      memory: 400Mi
  retention: 15d
