apiVersion: monitoring.coreos.com/v1
kind: Prometheus
metadata:
  labels:
    app: prometheus-example
  name: prometheus-example
spec:
  image: prom/prometheus:v2.7.1
  nodeSelector:
    group: monitoring
  replicas: 1
  resources:
    limits:
      cpu: 1000m
      memory: 2Gi
    requests:
      cpu: 500m
      memory: 400Mi
  retention: 15d
  storage:
    volumeClaimTemplate:
      spec:
        resources:
          requests:
            storage: 200Gi
        storageClassName: gp3-prom
  tolerations:
  - effect: NoSchedule
    key: group
    operator: Equal
    value: monitoring

---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  labels:
    app: prometheus-example
  name: prometheus-example-ingress
spec:
  rules:
  - host: prometheus.example.com
    http:
      paths:
      - backend:
          service:
            name: prometheus-example
            port:
              number: 9090
        path: /
        pathType: Prefix
