name: prometheus-example
kind: Prometheus
image: prom/prometheus:v2.7.1
retention: 15d
replicas: 1
resources:
  requests:
    memory: 400Mi
    cpu: 500m
  limits:
    memory: 2Gi
    cpu: 1000m
storage:
  size: 200Gi
  className: gp3-prom
node_selector:
  group: monitoring
ingress:
  host: prometheus.example.com
