apiVersion: monitoring.coreos.com/v1
kind: Prometheus
metadata:
  labels:
    app: example2
  name: example2
spec:
  image: prom/prometheus:v2.7.1
  nodeSelector:
    group: monitoring
  replicas: 1
  resources:
    limits:
      cpu: 1000m
      memory: 2Gi
    requests:
      cpu: 500m
      memory: 400Mi
  retention: 15d
  storage:
    volumeClaimTemplate:
      spec:
        resources:
          requests:
            storage: 200Gi
        storageClassName: gp3-prom
  tolerations:
  - effect: NoSchedule
    key: group
    operator: Equal
    value: monitoring

---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  labels:
    app: example2
  name: example2-ingress
spec:
  rules:
  - host: example.com
    http:
      paths:
      - backend:
          service:
            name: example2
            port:
              number: 9090
        path: /
        pathType: Prefix

---
apiVersion: v1
kind: ServiceAccount
automountServiceAccountToken: true
metadata:
  annotations:
    eks.amazonaws.com/role-arn: arn:aws:iam::123456789012:role/prometheus-role
  labels:
    app: example2
  name: prometheus-example2

---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app: example2
  name: example2-role
rules:
- apiGroups:
  - ''
  resources:
  - nodes
  - nodes/proxy
  - services
  - endpoints
  - pods
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - extensions
  resources:
  - ingresses
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - networking.k8s.io
  resources:
  - ingresses
  verbs:
  - get
  - list
  - watch
- nonResourceURLs:
  - /metrics
  verbs:
  - get

---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  labels:
    app: example2
  name: example2-role-binding
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: example2-role
subjects:
- kind: ServiceAccount
  name: prometheus-example2
  namespace: default
